name: Export and Upload MahjongSoul Data

on:
  schedule:
    - cron: '30,35,40,45,50,55 1 * * 5-7'
    # 9:00 PM to 9:50 PM EST == 02:00–02:50 UTC
    - cron: '0,10,20,30,35,40,45,50,55 2 * * 5-7'
    # 10:00 PM to 10:50 PM EST == 03:00–03:50 UTC
    - cron: '0,10,20,30,35,40,45,50,55 3 * * 5-7'
    # 11:00 PM to 11:30 PM EST == 04:00–04:30 UTC
    - cron: '0,10,20,30,35,40,45,50,55 4 * * 5-7'
    # Run at least once a day around midnight
    - cron: '0 5 * * *'
  workflow_dispatch:  # Allows manual trigger from the GitHub UI

jobs:
  run-export:
    runs-on: ubuntu-latest

    env:
      MJS_SECRET: ${{ secrets.MJS_SECRET }}
      CSV_OUTPUT_DIR: output
      MJS_SEASON_ID: 1

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ▶️ Run mjs.py
        run: |
          python mjs.py

      - name: ☁️ Upload output.csv to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'  # Change if your bucket is in a different region
          SOURCE_DIR: ${{ env.CSV_OUTPUT_DIR }}  # Uploads from current directory
          DEST_DIR: 'results'  # Folder in your S3 bucket
